# Ref https://docs.docker.com/compose/compose-file/#/version-2
version: '2'

services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile-development
    volumes:
      - .:/var/app
      - /var/app/node_modules
    ports:
      - 8080:8080